[package]
name = "theseus"
version = "0.1.0"
edition = "2021"
description = "Next-gen experimental balenaSupervisor"
homepage = "https://github.com/balena-io-experimental/theseus"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/balena-io-experimental/theseus"
publish = false

[dependencies]
axum = { version = "0.8.4", default-features = false, features = [
  "tokio",
  "http1",
] }
hyper = "1.6.0"
hyper-util = { version = "0.1.14", default-features = false, features = [
  "http1",
  "client-legacy",
  "tokio",
] }
hyper-tls = "0.6.0"
tokio = { version = "1.45.1", default-features = false, features = [
  "rt-multi-thread",
  "macros",
  "time",
  "fs",
] }
tower-http = { version = "0.6.6", default-features = false, features = [
  "trace",
] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [
  "env-filter",
  "fmt",
  "registry",
  "ansi",
] }
anyhow = "1.0.98"
reqwest = { version = "0.12", default-features = false, features = [
  "json",
  "rustls-tls",
  "brotli",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2"
rand = "0.9.1"
async-trait = "0.1"
clap = { version = "4.0", features = ["derive", "env"] }

[dev-dependencies]
mockito = { version = "1.0", default-features = false }
tokio-test = "0.4"
tempfile = "3.0"

[profile.release]
opt-level = "z"
codegen-units = 1
