[package]
name = "helios"
version = "0.2.7"
edition = "2021"
description = "Balena's on-device agent"
homepage = "https://github.com/balena-io-experimental/helios"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/balena-io-experimental/helios"
publish = false

[dependencies]
axum = { version = "0.8.4", default-features = false, features = [
  "tokio",
  "http1",
] }
hyper = "1.6.0"
hyper-util = { version = "0.1.14", default-features = false, features = [
  "http1",
  "client-legacy",
  "tokio",
] }
hyper-tls = "0.6.0"
tokio = { version = "1.45.1", default-features = false, features = [
  "rt-multi-thread",
  "macros",
  "time",
  "fs",
] }
tower-http = { version = "0.6.6", default-features = false, features = [
  "trace",
] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [
  "env-filter",
  "fmt",
  "registry",
  "ansi",
] }
anyhow = "1.0.98"
reqwest = { version = "0.12", default-features = false, features = [
  "json",
  "rustls-tls",
  "brotli",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2"
rand = "0.9.1"
async-trait = "0.1"
clap = { version = "4.0", features = ["derive", "env"] }
dirs = "6.0.0"
uuid = { version = "1.0", features = ["v4"] }
mahler = { version = "0.17.0" }
bollard = "0.19.1"
futures-lite = { version = "2.6.0", default-features = false }

[dev-dependencies]
mockito = { version = "1.0", default-features = false }
tempfile = "3.0"

[profile.release]
opt-level = "z"
codegen-units = 1
