version: '2.4'

services:
  helios:
    build: ./
    # This is needed so the service can bind to the same port as the
    # supervisor after stopping it. This should go away eventually so
    # no other features that require host networking should be introduced
    # on this service
    network_mode: host
    restart: on-failure
    labels:
      # Needed to get access to supervisor api variables
      # and credentials
      io.balena.features.supervisor-api: '1'
      # Needed for access to DOCKER_HOST
      io.balena.features.balena-socket: '1'
      # Needed to stop the supervisor service
      io.balena.features.dbus: '1'
      # Needed to get access to the API credentials
      io.balena.features.balena-api: '1'
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    volumes:
      # Base directory for app configuration and update locks
      - cache:/tmp/balena-supervisor
      # The legacy volume is only needed while the proxy is needed. Eventually
      # supervisor data should use a volume rather than a directory on the host
      - legacy:/mnt/legacy

volumes:
  cache:
    driver: local
    driver_opts:
      type: none
      o: bind,X-mount.mkdir=0755
      device: /tmp/balena-supervisor

  legacy:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/resin-data/balena-supervisor
