version: '2.4'

services:
  sut:
    build: ./integration
    depends_on:
      helios-api:
        condition: service_started

  helios-api:
    build: ./
    image: helios
    command: socat TCP-LISTEN:80,reuseaddr,fork UNIX-CONNECT:/tmp/run/helios.sock
    depends_on:
      helios:
        condition: service_healthy
    volumes:
      - runtime:/tmp/run
    healthcheck:
      test: ['CMD', 'wget', '-O', '-', '-q', 'http://127.0.0.1/v3/ping']

  # Override default configurations
  helios:
    # Set-up required variables
    environment:
      BALENA_DEVICE_UUID: 'test-uuid'
      BALENA_SUPERVISOR_PORT: 48484
      DOCKER_HOST: 'tcp://docker:2375'
    depends_on:
      docker:
        condition: service_healthy

  docker:
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ''
    command: --tls=false
    healthcheck:
      test: ['CMD', 'docker', 'ps']
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  runtime:
    driver_opts:
      type: tmpfs
      o: ''
      device: tmpfs
